
# Home Assistant Configuration --
# Owner: rado0x54

# Replacing meta-component "default config" with individual entries.
automation: !include_dir_merge_list automations
config:
frontend:
  themes: !include themes.yaml
history:
logbook:
map:
mobile_app:
person:
script: !include_dir_merge_named scripts
ssdp:
sun:
system_health:
# Updater
updater:
  reporting: false
zeroconf:

# Automatic Discovery
discovery:

homeassistant:
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 30
  unit_system: metric
  time_zone: America/New_York
  name: NYC509
  external_url: !secret external_url
  allowlist_external_dirs:
    - /webshare

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # server_host: 127.0.0.1
  # Update this line to be your domain
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 127.0.0.1


# Custom Recorder:
recorder:
  db_url: !secret recorder_db_url

# Mobile Support (iOS)
# Disabled from version 2.0 of the App.
# Not using actionable notifications atm.
# ios:

# Streaming Support
stream:

# MQTT
mqtt:
  broker: localhost
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password

# Modernform Fans.
modernforms:
  - host: openwrt.lan:8080/mf-br
    name: Bedroom
    light: true
  - host: openwrt.lan:8080/mf-lr
    name: Living Room
    light: true
  - host: openwrt.lan:8080/mf-of
    name: Office
    light: true

# Wake up light
somneo:
  host: somneo.lan

# TPLink
tplink:
  discovery: false
  dimmer:
    - host: sw-entry.lan
    - host: sw-hallway.lan
    - host: sw-kitchen.lan

# RoboRock
vacuum:
  - platform: xiaomi_miio
    host: rockrobo.lan
    token: !secret miio_token
    name: "Smartin junior"

# Camera
camera:
  - platform: generic
    name: Home Cam Office
    still_image_url: http://yi-cam-1.lan:8080/cgi-bin/snapshot.sh
    stream_source: rtsp://yi-cam-1.lan/ch0_0.h264
  - platform: generic
    name: Home Cam Street
    still_image_url: http://yi-cam-2.lan:8080/cgi-bin/snapshot.sh
    stream_source: rtsp://yi-cam-2.lan/ch0_0.h264
  - platform: ffmpeg
    name: Babycam
    input: -re -i rtsp://eufy-cam-1.lan/live0

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_nyc509_bot_key
    allowed_chat_ids:
      - !secret telegram_nyc509_chatid
      - !secret telegram_nyc509_test_chatid
      - !secret telegram_rado0x54_chatid
      - !secret telegram_jordan_chatid

# Carson Living
carson:
 username: !secret carson_username
 password: !secret carson_password


# Text to speech
tts:
  - platform: google_translate

media_player:
 - platform: samsungtv_custom
   host: samsung.lan
   port: 8002
   mac: 00:C3:F4:41:2D:FB
   sourcelist: '{"AppleTV": "KEY_HDMI1", "Switch": "KEY_HDMI2", "PlayStation": "KEY_HDMI3"}'
   protocol: ws

# Workday Sensor
binary_sensor:
  - platform: workday
    country: US
    province: NY

# Shell Commands
shell_command:
  link_latest: '(cd {{ working_directory }} && ln -fs $(ls -t {{ ls_expression }} | head -n 1) {{ latest_filename }})'
  copy: 'cp {{ src_filename }} {{ dest_filename }}'

# Includes
notify: !include_dir_merge_list notify/
switch: !include switches.yaml
climate: !include climate.yaml
group: !include groups.yaml
zone: !include zones.yaml
homekit: !include homekit.yaml
sensor: !include_dir_merge_list sensors/
input_select: !include_dir_merge_named input_select/


