# Only open Bedroom on Workdays.
- alias: 'Blinds - Auto Open'
  trigger:
    - platform: sun
      event: sunrise
    - platform: time
      at: '06:30:00'
  condition:
    - condition: sun
      after: sunrise
    - condition: time
      after: '06:30:00'
  action:
    service: cover.open_cover
    data_template:
      entity_id: >
        group.living_room_blinds
        {%- if is_state('binary_sensor.workday_sensor', 'on') -%}
          , cover.blind_bedroom
        {%- endif %}

- alias: 'Blinds - Auto Close'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:25:00'
  action:
    service: cover.close_cover
    entity_id: group.living_room_blinds, cover.blind_bedroom


