# MQTT HVAC uses individual command topics but HeatPump does not
# so use an automation to push the commands to the HP (only one automation needed due to wildcards):
- alias: 'Climate - Redirect all MQTT HVAC commands'
  trigger:
    - platform: mqtt
      topic: +/heatpump/_set/+
  action:
    - service: mqtt.publish
      data_template:
        topic:  '{{ trigger.topic.split("/")[0] + "/heatpump/set" }}'
        payload: >
          {% if trigger.topic.split("/")[-1] == "mode" %}
            {% if trigger.payload|upper == "OFF" %}
              {"power":"OFF"}
            {% elif trigger.payload == "fan_only" %}
              {"power":"ON","mode":"FAN"}
            {% else %}
              {{ "{\"power\":\"ON\",\"mode\":"|safe + trigger.payload|upper|tojson + "}" }}
            {% endif %}
          {% else %}
            {{ "{" + trigger.topic.split("/")[-1]|tojson + ":" + trigger.payload|tojson + "}" }}
          {% endif %}
