- alias: 'Notification - OpenClose'
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.openclose_13
      - binary_sensor.openclose_14
      - binary_sensor.openclose_24
      - binary_sensor.openclose_26
      - binary_sensor.openclose_27
      - binary_sensor.openclose_38
    from: 'off'
    to: 'on'
  condition:
    condition: template # Throttle by not triggering push messages if triggered in the last 10 seconds
    value_template: >
      {{ not state_attr('automation.notification_openclose','last_triggered') or (as_timestamp(now()) - as_timestamp(state_attr('automation.notification_openclose','last_triggered'))) > 10 }}
  action:
    service: notify.all_residents
    data_template:
      title: "509 2R {{ trigger.to_state.attributes.friendly_name[:-10] }}"
      # Remove " OpenClose" Suffix from Binary Sensor Friendly Name
      message: 'The {{ trigger.to_state.attributes.friendly_name[:-10] }} was opened at {{ now().strftime("%H:%M %m/%d") }}!'
      data:
        push:
          thread-id: "openclose-notification-group"
