- alias: 'Notification - Main Door'
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_13
    from: 'off'
    to: 'on'
  action:
    service: notify.all_residents
    data:
      title: "509 2R door"
      message: 'The main door was opened at {{ now().strftime("%H:%M %m/%d") }}!'
      data:
        push:
          thread-id: "main-door-notification-group"
