- platform: darksky
  api_key: !secret darksky-key
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - temperature
    - temperature_high
    - temperature_low
    - precip_intensity
    - precip_probability
    - sunset_time
    - uv_index
    - hourly_summary
  scan_interval: '00:05:00'
