- platform: template
  sensors:
    any_sonos_playing:
      friendly_name: "Sonos Playing"
      value_template: >-
        {{ 
          is_state('media_player.living_room', 'playing') or
          is_state('media_player.bathroom', 'playing') or
          is_state('media_player.office', 'playing')
        }}
