- alias: Change Magic Cube Face
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: mi_magic_cube
  condition:
    condition: template
    # event < 7000 are face orientation UNLESS they are a rotation (gesture 7 & 8)
    value_template: "{{ trigger.event.data.event < 7000 and trigger.event.data.gesture < 7 }}"
  action:
     service: input_select.select_option
     data_template:
      entity_id: input_select.magic_cube_mode
      option: "Face{{ ( trigger.event.data.event / 1000) | round() }}"