### Toggle Desk Lamp via Dimmer
- alias: 'Toggle Desk Lamp via Dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
        id: tradfri_wireless_dimmer
  action:
    service: light.turn_on
    #entity_id: cover.blind_living_room_s
    data_template:
      entity_id: light.desk
      brightness: >
        {% set bri = state_attr('light.desk', 'brightness') | int %}
        {% if trigger.event.data.event == 2002 %}
          {{ [bri+51, 255] | min }}
        {% else %}
          {{ [bri-51, 0] | max }}
        {% endif %}


### Toggle Desk Lamp via Magic Cube Face 1
- alias: 'Toggle Desk Lamp via Magic Cube'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
        id: mi_magic_cube
        event: 1001
  action:
    service: light.toggle
    entity_id: light.desk

### Dimm Desk Lamp via Magic Cube Face 1
- alias: 'Dim Desk via Magic Cube'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
        id: mi_magic_cube
  condition:
    - condition: state
      entity_id: input_select.magic_cube_mode
      state: 'Face1'
    - condition: state
      entity_id: light.desk
      state: 'on'
    - condition: template
      # Gesture 7 & 8 are rotations
      value_template: '{{ trigger.event.data.gesture > 6 }}'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.desk
      # trigger.event.data.event is degrees * 100
      # range in half a rotation.
      brightness: >
        {% set bri = state_attr('light.desk', 'brightness') | int %}
        {% set adj = ((trigger.event.data.event / 18000) * 255) | int %}
        {{ bri + adj }}

