alias: 'Send notification when sun rises'
trigger:
  - platform: time
    at: '07:00:00'
action:
  service: notify.all_residents
  data:
    title: "NYC509 - Céline Forecast"
    message: >
      {{ states('sensor.dark_sky_summary_0d') }}
      Temp 
      {{ states('sensor.dark_sky_daytime_high_temperature_0d') }}
      ({{ ((float(states('sensor.dark_sky_daytime_high_temperature_0d')) * 9 / 5 )  +  32) | round(1) }})-
      {{ states('sensor.dark_sky_overnight_low_temperature_0d') }}
      ({{ ((float(states('sensor.dark_sky_overnight_low_temperature_0d')) * 9 / 5 )  +  32) | round(1) }})°C(F). 
      Precip 
      {{ states('sensor.dark_sky_precip_intensity_0d') }}({{ states('sensor.dark_sky_precip_probability_0d') }}%). 
      UV 
      {{ states('sensor.dark_sky_uv_index_0d') }}.
      

