- alias: 'Baby - Crying'
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_crying_detected
    to: 'on'
  action:
    - service: notify.all_residents
      data_template:
        title: '509 2N {{ trigger.to_state.attributes.friendly_name }}'
        # event_time is in millis
        # message: 'Baby cried at {{ trigger.to_state.attributes.event_time | multiply(0.001) | timestamp_custom("%H:%M %m/%d") }}!'
        message: 'Baby cried at {{ now().strftime("%H:%M %m/%d") }}!'
        data:
          attachment:
            url: '{{ trigger.to_state.attributes.thumbnail }}'
            content-type: jpg
            hide-thumbnail: false
          push:
            thread-id: "baby-notification-group"
            sound:
              name: default
              critical: 1
              volume: 0.8
          sticky: true
          persistent: true
          tag: persistent
    - service: camera.record
      entity_id: camera.babycam
      data:
        filename: '/webshare/recordings/Babycam_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
        duration: 60
    # Cooldown until next trigger
    - delay:
        seconds: 120
